### PR TITLE
silent option

### PR DESCRIPTION
**Pull request by smelukov**
Sometimes I don't want to see `webpack-fix-style-only-entries: removing js from style only module ...` messages

### CODE REVIEW

**Comment by fqborges** [comment]
Thanks

**Comment by smelukov** [comment]
Seems like you forget to publish the package ;)
`npm i webpack-fix-style-only-entries@0.0.4`
> No matching version found for webpack-fix-style-only-entries@0.0.4

**Comment by fqborges** [comment]
There is actually a bug on the silent option code. I am fixing it and will publish soon.

**Comment by fqborges** [comment]
done!

**Pull request merged**
